import type { ItemType } from '$lib/types';

export const DEFAULT_EQUIPMENTS: ItemType[] = [
	{ name: 'Rope' },
	{ name: 'Torch' },
	{ name: 'Backpack' },
	{ name: 'Bedroll' },
	{ name: 'Ration' },
	{ name: 'Basic Armour' }
];

export const EQUIPMENTS: ItemType[] = [
	...DEFAULT_EQUIPMENTS,
	{ name: 'Plate Armour' },
	{ name: 'Shield' },
	{ name: 'Crowbar' },
	{ name: 'Pickaxe' },
	{ name: 'Shovel' },
	{ name: 'Hammer and Chisel' },
	{ name: 'Chain' },
	{ name: '25cm Pole' },
	{ name: 'Whetstone' },
	{ name: 'Bear Trap' },
	{ name: 'Bullseye Lantern' },
	{ name: 'Grappling Hook' },
	{ name: 'Grease' },
	{ name: 'Manacles' },
	{ name: 'Lockpicks' },
	{ name: 'Bag of Marbles' },
	{ name: 'Set of Files' },
	{ name: 'Mirror on a Handle' },
	{ name: '75cm Silk Rope' },
	{ name: 'Caltrops' },
	{ name: 'Dose of Venom' },
	{ name: 'Flask of Acid' },
	{ name: 'Hooded Lantern' },
	{ name: "Alchemist's Fire" },
	{ name: 'Musical Instrument' },
	{ name: 'Lock and Key' },
	{ name: 'Book of Alchem' },
	{ name: 'Book of Mythology' },
	{ name: 'Book of Religio' },
	{ name: 'Book of Magi' },
	{ name: 'Book of Histor' },
	{ name: 'Book of Language' },
	{ name: 'Dose of Medicine' },
	{ name: 'Chalk' },
	{ name: 'Writing Kit' },
	{ name: 'Antitoxin' },
	{ name: 'Holy Water' },
	{ name: 'Compass' },
	{ name: 'Spell Scroll' },
	{ name: 'Holy Relic' }
];
